----------dangerzone luas
require("dz/[HYD]dzjoin")
require("dz/[HYD]dz_sniffer")
require("dz/[HYD]drone_killer")
require("dz/[HYD]barrel_killer")
require("dz/[HYD]distance_indicator")
---require("dz/[HYD]dz_Barrel_chicken_esp")
require("dz/[HYD]all_betterboxes")
require("dz/[HYD]dz_auto_respawn")
require("dz/[HYD]dz_crosshair_indicators")
require("dz/[HYD]dz_esp")
--require("dz/[HYD]dz_highscores")
require("dz/[HYD]dz_plisthack")
require("dz/[HYD]dz_remove_grass")
require("dz/[HYD]dz_shieldbot")
require("dz/[HYD]dz_speedHVH")
require("dz/[HYD]Force aspect ratio")
---require("dz/[HYD]drone_aimbot")
require("dz/[HYD]Punchbot")
-----------------global luas
require("dz/[HYD]Ladder Movement")
require("dz/[HYD]hitsound")
require("dz/[HYD]Thirdperson")
require("dz/[HYD]hit_total_ratio")
require("dz/[HYD]crosshair_hitlog")
require("dz/[HYD]custom_scope_lines")
client.color_log(255, 0, 255, "DangerZone GODLIKE Dragon Public.lua loaded successfully.")
client.color_log(255, 0, 255, "Lua Version:V6.4[Release] Last Update Time:2025/10/14")
client.color_log(255, 0, 255, "Please check your computer's RAM.")
client.color_log(255, 0, 255, "If RAM less than 24GB, please add some virtual memory.")
client.color_log(255, 0, 255, "Insufficient memory may cause performance issues such as crashes.")
client.color_log(255, 0, 255, "GL&HF!")
client.color_log(255, 0, 255, "Author:HuYiDao. Owned by DangerZoneCoreTeam.")
client.color_log(255, 0, 255, "OurWebSite:https://www.abchvh.cc/")
