require("dz/[HYD]dz_auto_respawn")
require("dz/[HYD]dz_remove_grass")
require("dz/[HYD]dz_speedHVH")
require("dz/[HYD]dz_shieldbot")
client.color_log(255, 0, 255, "DangerZone GODLIKE Dragon Public[Lite].lua loaded successfully.")
client.color_log(255, 0, 255, "Lua Version:V6.2[Release] Last Update Time:2025/10/1")
client.color_log(255, 0, 255, "Please check your computer's RAM.")
client.color_log(255, 0, 255, "If RAM less than 24GB, please add some virtual memory.")
client.color_log(255, 0, 255, "Insufficient memory may cause performance issues such as crashes.")
client.color_log(255, 0, 255, "GL&HF!")
client.color_log(255, 0, 255, "Author:HuYiDao. Owned by DangerZoneCoreTeam.")
client.color_log(255, 0, 255, "OurWebSite:https://www.abchvh.cc/")
